eureka: 
  client: 
    serviceUrl: 
      defaultZone: "http://localhost:8888/eureka/"
management: 
  security: 
    enabled: false
message: 
  greeting: "Hello! Product-service configuration"
server: 
  port: 8000
